import Foundation

// MARK: - EnvGenerateCommand
//
// Handles: shi env generate hosts|caddyfile-local --env <env> [--apply] [--no-per-tenant]
//
// `generate hosts`          → HostsGenerator.generate()
// `generate caddyfile-local`→ CaddyfileLocalGenerator.generate()
//
// Spec: features/shi-env-local-prod-parity-2026-05-31.md §3.2 + §5 TP-SELP-06 + TP-SELP-07

public struct EnvGenerateCommand: Sendable {

    public struct Options: Sendable {
        /// Subcommand: "hosts" | "caddyfile-local"
        public var subcommand: String
        /// Environment address (e.g. "obyw-one.obyw-one.local")
        public var envAddress: String
        /// Write output to disk (requires sudo for hosts).
        public var apply: Bool
        /// Omit per-tenant client entries.
        public var skipPerTenant: Bool
        public var jsonOutput: Bool

        public init(
            subcommand: String,
            envAddress: String,
            apply: Bool = false,
            skipPerTenant: Bool = false,
            jsonOutput: Bool = false
        ) {
            self.subcommand = subcommand
            self.envAddress = envAddress
            self.apply = apply
            self.skipPerTenant = skipPerTenant
            self.jsonOutput = jsonOutput
        }
    }

    private let shikkiRoot: URL

    public init(shikkiRoot: URL = URL(fileURLWithPath: NSHomeDirectory()).appendingPathComponent(".shikki")) {
        self.shikkiRoot = shikkiRoot
    }

    @discardableResult
    public func run(
        options: Options,
        outputStream: inout some TextOutputStream
    ) async throws -> Int32 {
        // Load manifest
        let manifest = try loadManifest(address: options.envAddress)

        switch options.subcommand {

        case "hosts":
            let gen = HostsGenerator()
            let opts = HostsGenerator.Options(apply: options.apply, skipPerTenant: options.skipPerTenant)
            let result = try gen.generate(manifest: manifest, options: opts)
            if options.jsonOutput {
                let entries = result.entries.map { ["ip": $0.ip, "hostname": $0.hostname] }
                if let data = try? JSONSerialization.data(withJSONObject: entries, options: .prettyPrinted),
                   let str = String(data: data, encoding: .utf8) {
                    outputStream.write(str + "\n")
                }
            } else {
                outputStream.write("# Generated by shi env generate hosts --env \(options.envAddress)\n")
                outputStream.write(result.block + "\n")
                if options.apply {
                    outputStream.write("\n✓ Written to /etc/hosts (\(result.entries.count) entries)\n")
                } else {
                    outputStream.write("\n# Pass --apply to write to /etc/hosts (requires sudo)\n")
                }
            }
            return 0

        case "caddyfile-local":
            let gen = CaddyfileLocalGenerator()
            let opts = CaddyfileLocalGenerator.Options(skipPerTenant: options.skipPerTenant)
            let result = gen.generate(manifest: manifest, options: opts)
            if options.jsonOutput {
                let obj: [String: Any] = [
                    "hosts": result.hosts,
                    "caddyfile": result.caddyfile
                ]
                if let data = try? JSONSerialization.data(withJSONObject: obj, options: .prettyPrinted),
                   let str = String(data: data, encoding: .utf8) {
                    outputStream.write(str + "\n")
                }
            } else {
                outputStream.write("# Generated by shi env generate caddyfile-local --env \(options.envAddress)\n")
                outputStream.write("# Hosts: \(result.hosts.joined(separator: ", "))\n\n")
                outputStream.write(result.caddyfile + "\n")
                if options.apply {
                    let caddyPath = shikkiRoot.appendingPathComponent("run/local/Caddyfile")
                    try FileManager.default.createDirectory(
                        at: caddyPath.deletingLastPathComponent(),
                        withIntermediateDirectories: true
                    )
                    try result.caddyfile.write(to: caddyPath, atomically: true, encoding: .utf8)
                    outputStream.write("\n✓ Written to \(caddyPath.path)\n")
                } else {
                    outputStream.write("\n# Pass --apply to write to \(shikkiRoot.appendingPathComponent("run/local/Caddyfile").path)\n")
                }
            }
            return 0

        default:
            fputs("Usage: shi env generate <hosts|caddyfile-local> --env <addr> [--apply]\n", stderr)
            return 1
        }
    }

    // MARK: Private

    private func loadManifest(address: String) throws -> EnvironmentManifest {
        let parts = address.components(separatedBy: ".")
        guard parts.count == 3 else {
            throw EnvGenerateError.invalidAddress(address)
        }
        let (workspace, project, env) = (parts[0], parts[1], parts[2])
        let base = shikkiRoot
            .appendingPathComponent("workspaces/\(workspace)/projects/\(project)")
            .appendingPathComponent(".shikki/env/\(env).json")
        let data = try Data(contentsOf: base)
        return try EnvironmentManifest.decode(fromJSON: data)
    }
}

public enum EnvGenerateError: Error, LocalizedError {
    case invalidAddress(String)
    case manifestNotFound(String)

    public var errorDescription: String? {
        switch self {
        case .invalidAddress(let a):
            return "Invalid env address '\(a)'. Expected <workspace>.<project>.<env>"
        case .manifestNotFound(let p):
            return "Manifest not found at \(p)"
        }
    }
}
